# Generated by Django 5.1.4 on 2025-01-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cve', models.CharField(max_length=100, unique=True)),
                ('max_cvss', models.FloatField(blank=True, null=True)),
                ('type_vulnerability', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('lien', models.URLField()),
                ('resume', models.TextField()),
                ('lien_article', models.URLField(blank=True, null=True)),
                ('resume_article', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
